### ISSUE TITLE
Message should display the winning

### ISSUE THREAD

**Issue by Xouxs** [LaMonF/FDJ_SLACK#10]
To easily see if we won something we should display :

Gain au tirage : X€

Where X is the daily winning based on this link FAQ : https://www.fdj.fr/jeux/jeux-de-tirage/loto/ 

![dm_1488303986_loto_quels-sont-les-gains_tableau-des-gains_mise-2-20-euros](https://user-images.githubusercontent.com/4569469/46216823-b7933000-c340-11e8-94d5-fc0cd626e94a.jpg)
![dm_1488303993_loto_quels-sont-les-gains_tableau-des-gains_mise-3-euros](https://user-images.githubusercontent.com/4569469/46216821-b6fa9980-c340-11e8-86e7-dee233d2c3f8.jpg)
![dm_1488304001_loto_quels-sont-les-gains_tableau-des-gains_mise-5-euros](https://user-images.githubusercontent.com/4569469/46216822-b6fa9980-c340-11e8-9fbf-64f16f55d3a1.jpg)

**Comment by Xouxs** [comment]
Maybe related to #9

**Comment by LaMonF** [comment]
The first implementation is based on the first table only

**Comment by LaMonF** [comment]
Done in #27
