### ISSUE TITLE
Go : add timer to post everyday at 9pm the loto result.

### ISSUE THREAD

**Issue by Xouxs** [LaMonF/FDJ_SLACK#11]
see time.ticker.

Maybe only send the monday, wednesday and saturday.

**Comment by LaMonF** [comment]
The current master version (python) is using the CronTab. 
The current Go implementation in DEV brings new features triggered by Slack command lines which require backend server running. Thus, this new version will not be usable with Crontab and it will need the introduction of the timer.ticker.

As a lottery can happen in friday or sunday (bonus lottery) I will consider sending feebacks every day.

**Comment by LaMonF** [comment]
#14
